CREATE TABLE IMDB.ACTRESS (
       ID INTEGER NOT NULL
     , NAME VARCHAR(255)
     , MOVIE_ID VARCHAR(255)
     , ROLE VARCHAR(255)
     , ORDER VARCHAR(5)
     , PRIMARY KEY (ID)
);

CREATE TABLE IMDB.AKA_NAMES (
       ID INTEGER NOT NULL
     , NAME VARCHAR(255)
     , AKA_NAME CHAR(10)
     , PRIMARY KEY (ID)
);

CREATE TABLE IMDB.AKA_TITLES (
       ID INTEGER NOT NULL
     , MOVIE_ID VARCHAR(255)
     , AKA_TITLE VARCHAR(255)
     , INFO VARCHAR(255)
     , PRIMARY KEY (ID)
);

CREATE TABLE IMDB.ALTERNATE_VERSIONS (
       ID INTEGER NOT NULL
     , MOVIE_ID VARCHAR(255)
     , ALTERATION CHAR(1048576)
     , PRIMARY KEY (ID)
);

CREATE TABLE IMDB.CERTIFICATES (
       ID INTEGER NOT NULL
     , MOVIE_ID VARCHAR(255)
     , COUNTRY VARCHAR(100)
     , CERTIFICATE VARCHAR(255)
     , PRIMARY KEY (ID)
);

CREATE TABLE IMDB.CINEMATOGRAPHERS (
       ID INTEGER NOT NULL
     , NAME VARCHAR(255)
     , MOVIE VARCHAR(255)
     , PRIMARY KEY (ID)
);

CREATE TABLE IMDB.COLOR_INFO (
       ID INTEGER NOT NULL
     , MOVIE_ID VARCHAR(255)
     , COLOR VARCHAR(100)
     , PRIMARY KEY (ID)
);

CREATE TABLE IMDB.COUNTRIES (
       ID INTEGER NOT NULL
     , MOVIE_ID VARCHAR(255)
     , COUNTRY VARCHAR(100)
     , PRIMARY KEY (ID)
);

CREATE TABLE IMDB.DIRECTORS (
       ID INTEGER NOT NULL
     , NAME VARCHAR(255)
     , MOVIE VARCHAR(255)
     , PRIMARY KEY (ID)
);

CREATE TABLE IMDB.DISTRIBUTORS (
       ID INTEGER NOT NULL
     , MOVIE_ID VARCHAR(255)
     , DISTRIBUTOR VARCHAR(255)
     , PRIMARY KEY (ID)
);

CREATE TABLE IMDB.EDITORS (
       ID INTEGER NOT NULL
     , NAME VARCHAR(255)
     , MOVIE VARCHAR(255)
     , PRIMARY KEY (ID)
);

CREATE TABLE IMDB.GENRES (
       ID INTEGER NOT NULL
     , MOVIE_ID VARCHAR(255)
     , GENRE VARCHAR(100)
     , PRIMARY KEY (ID)
);

CREATE TABLE IMDB.KEYWORDS (
       ID INTEGER NOT NULL
     , MOVIE_ID VARCHAR(255)
     , KEYWORD VARCHAR(255)
     , PRIMARY KEY (ID)
);

CREATE TABLE IMDB.LANGUAGE (
       ID INTEGER NOT NULL
     , MOVIE_ID VARCHAR(255)
     , LANGUAGE VARCHAR(100)
     , PRIMARY KEY (ID)
);

CREATE TABLE IMDB.MOVIE (
       MID VARCHAR(255) NOT NULL
     , TITLE VARCHAR(255) NOT NULL
     , DATE CHAR(4) NOT NULL
     , PRIMARY KEY (MID)
);

CREATE TABLE IMDB.MOVIE_LINKS (
       ID INTEGER NOT NULL
     , MOVIE_ID VARCHAR(255)
     , LINK VARCHAR(255)
     , PRIMARY KEY (ID)
);

CREATE TABLE IMDB.PRODUCERS (
       ID INTEGER NOT NULL
     , NAME VARCHAR(255)
     , MOVIE_ID VARCHAR(255)
     , ROLE VARCHAR(255)
     , PRIMARY KEY (ID)
);

CREATE TABLE IMDB.PRODUCTION_DESIGNERS (
       ID INTEGER NOT NULL
     , NAME VARCHAR(255)
     , MOVIE VARCHAR(255)
     , PRIMARY KEY (ID)
);

CREATE TABLE IMDB.PROD_COM (
       ID INTEGER NOT NULL
     , MOVIE_ID VARCHAR(255)
     , PROD_COM VARCHAR(255)
     , COUNTRY VARCHAR(10)
     , PRIMARY KEY (ID)
);

CREATE TABLE IMDB.QUOTES (
       ID INTEGER NOT NULL
     , MOVIE_ID VARCHAR(255)
     , PERSON VARCHAR(255)
     , QUOTE CHAR(100)
     , PRIMARY KEY (ID)
);

CREATE TABLE IMDB."RELEASE-DATES" (
       ID INTEGER NOT NULL
     , MOVIE_ID VARCHAR(255)
     , COUTNRY VARCHAR(255)
     , DATE VARCHAR(255)
     , INFO VARCHAR(255)
     , PRIMARY KEY (ID)
);

CREATE TABLE IMDB.WRITERS (
       ID INTEGER NOT NULL
     , NAME VARCHAR(255)
     , MOVIE VARCHAR(255)
     , PRIMARY KEY (ID)
);

CREATE TABLE IMDB.ACTOR (
       ID INTEGER NOT NULL
     , NAME VARCHAR(255) NOT NULL
     , MOVIE_ID VARCHAR(255) NOT NULL
     , ROLE VARCHAR(255)
     , ORDER VARCHAR(5)
     , PRIMARY KEY (ID)
);

